### ISSUE TITLE
javascript best practices 

### ISSUE THREAD

**Issue by mugishasam123** [billionsjoel/todo-app#5]
hey @billionsjoel ✋ while I was reviewing your codebase I found it well organized with best practice 🥇 

but they are still some issues to work on to better improve it.

- on below line you should consider creating a list node and bind it to ul as best practice  instead of overwriting string to ul 👍 

https://github.com/billionsjoel/todo-app/blob/a85dd821a34b4ecfa0059cca0ff244f503058ffb/src/modules/RenderTask.js#L21

**Comment by billionsjoel** [comment]
Hello @mugishasam123 ✋, that is quite a good eye, i did refactor the code to render the tasks using listnode, unfortunately in this usecase, the best way to render the tasks is to use innerHTML because we have a lot of SVG images and classes we would love to render with which is supported in innerHTML rather than using list node to append a single value.

This article [here](https://stackoverflow.com/questions/47951287/dynamically-add-li-to-ul-javascript/47951374) also suggests that as long as you use the tool in the right way then is isn't an issue that its a good practice in specific use cases that need it.

Thank you for noting that out 👍 .

**Comment by mugishasam123** [comment]
hey @billionsjoel  got what you said, and I will make sure to readme more about that

good work on solving issues stated 💯
